### ISSUE TITLE
No "http:" protocol prefix results in empty files being created.

### ISSUE THREAD

**Issue by keihin** [cecekpawon/Bandcamp-Yo-Ben#6]
As of a couple of weeks ago, Bandcamp-Yo-Ben downloads using FF-Greasemonkey and the "#Download WGET" feature have been failing. Previously it was working very well.)  The script runs from the download directory, and results in correctly named files of zero length.  Looking at the contents of the script (.bat) file, I see that the download URLs have no protocol specified.  Adding a protocol ("http:") to these URLs results in the downloads working correctly. 

Example non-working URL:
wget -c -O "01. ArtistName - AlbumName - SongName.mp3" "//popplers5.bandcamp.com/download/track?enc=mp3-128&fsig=123456&id=123456&stream=1&ts=123456.0" --no-check-certificate

Same URL, but working:
wget -c -O "01. ArtistName - AlbumName - SongName.mp3" "http://popplers5.bandcamp.com/download/track?enc=mp3-128&fsig=123456&id=123456&stream=1&ts=123456.0" --no-check-certificate

Unclear to me whether this is due to a change in the bandcamp.com website, a FF update, or something else.  It went from working to non-working without any changes to the plug-in.  It's nice to have a work-around, but it would be great if the resulting script didn't require these edits.

**Comment by cecekpawon** [comment]
Hello @keihin thx for reporting.. Could you please update the script & let me know if its ok for you now?

**Comment by keihin** [comment]
Updated.  Last few attempts have all been showing full protocol-included URLs.  Works.  Thanks.
