### ISSUE TITLE
Is there any way to add the release year to downloaded songs' file names?

### ISSUE THREAD

**Issue by camartinez1229** [cecekpawon/Bandcamp-Yo-Ben#7]
Hello, I've been using your script for a while now, and find it a great help. Thanks for your hard work!

However, it's been my experience that usually, songs download with incomplete metadata. I can fill in most of the missing stuff automatically because the file name has the track number, artist, album artist where applicable, album, and song title. But, there's no release year. So, if that's missing in the metadata, I have to look up the album web page for that info. Could you update the script to include the year? Looking up a few albums' HTML source, it looks like the release year is found like this:
   
```
<div class="tralbumData tralbum-credits">
                released #DATE#
                <meta itemprop="datePublished" content="yyyymmdd"/>           
</div>
```
I'm thinking it'd be easiest to parse the year from the content property in that meta tag? I'd greatly appreciate if you could look into that. Thanks for your time!

**Comment by cecekpawon** [comment]
Hello, sorry for late reply. You can try [this](https://gist.github.com/cecekpawon/57b3b536532d274177f6302fbf45ff82/raw/5e400456fd878eeb0ce0087b4c13154fa2bb3a8d/Bandcamp-Yo-Ben.user.js) beta version (download & drag into browser) & please reconfirm. Date will impact to: Songs / batch (wget) download filename including cover. You can (de)activate it via checkbox.

**Comment by camartinez1229** [comment]
That works perfectly. Thank you! I confirmed it works as is, adding the full release date to each song's file name, on one album page I tried it out on. I then tweaked the script to output just the year, since I only use the year in the date field when tagging my music.

**Comment by cecekpawon** [comment]
Enjoy :beers:
