### ISSUE TITLE
Not working on albums that are not free

### ISSUE THREAD

**Issue by aensaro** [cecekpawon/Bandcamp-Yo-Ben#8]
I just noticed that it stopped working:
The # sign does not appear anymore in front of the tracks for albums that are not free.
It only works for free albums.

Using violent Monkey and Chrome.

**Comment by aensaro** [comment]
Uh, wait. You said it works just with Tampermonkey... Never mind then.

**Comment by cecekpawon** [comment]
Basically it will work only with streamable contents 🍻
